### ISSUE TITLE
MVC 패턴 적용 및 모델에 대한 JUnit 테스트 코드 작성

### ISSUE THREAD

**Issue by tjwjdgus12** [2022-cau-design-pattern-09/life-game#12]
현재 Universe 클래스가 UI에도 관여하고 게임 로직에도 관여하는데,
구조를 파악하기 쉽고 테스트를 용이하게 하기위해 UI를 분리할 것을 제안합니다

**Comment by redjen8** [comment]
1) 게임 서비스에 대한 로직, 2) 서비스 로직을 JFrame으로 옮기는 로직
이렇게 두 개로 분리하면 될까요?

**Comment by tjwjdgus12** [comment]
이왕이면 View와 Controller도 분리되면 좋을 것 같습니다.
교수님이 이 과제에 MVC가 적용되면 좋을 것이라고 수업 때 말씀하셔서ㅎㅎ

**Comment by redjen8** [comment]
쉽지 않겠네요. ㅎㅎ
Model : 현재 진행되고 있는 논리적인 게임 진행 상황 혹은 관련 데이터
View : 사용자에게 보여지는 JFrame UI
Controller : JFrame UI로 게임 상태 변화를 Model에 전달
느낌이 될텐데, Model의 경우 JUnit 테스팅이 용이하지만 View, Controller는 Model과 비교하여 UI 적 요소가 들어가기 때문에 다소 어렵다고 느껴집니다. JUnit으로는 메서드만 테스트할 수 있는 것 같아 UI 적인 요소를 테스팅 할 때에는 다른 모듈의 개입이 필수적입니다.
[AssertJ](https://joel-costigliola.github.io/assertj/assertj-swing.html)와 같은 라이브러리도 같이 사용하면 좋을 것 같은데, 다른 아이디어 있으면 공유 부탁드리겠습니다.

**Comment by tjwjdgus12** [comment]
Model에 대한 테스트로 충분하지 않을까요? View나 Controller의 awt, swing의 함수들을 테스트할 필요는 없다고 생각합니다..!
