### ISSUE TITLE
Test Case에서 FigureNext를 테스트 하기 위한 함수 작성에 대한 도움 요청

### ISSUE THREAD

**Issue by SuperChobo** [2022-cau-design-pattern-09/life-game#20]
생각대로 잘 안되네요....
https://github.com/2022-cau-design-pattern-09/life-game/blob/df1d2a5d60b82fd7a3393872f79ec8e01b7785b8/HolubLife/test/com/holub/life/UniverseTest.java#L95-L187

**Comment by redjen8** [comment]
어느 메서드에서 도움이 필요하신가요?

**Comment by SuperChobo** [comment]
> 어느 메서드에서 도움이 필요하신가요?

UniverseTest에 nextTickTest_1 메소드에서 3x3칸으로 모든 셀이 활성화 되어있을 때, 다음 상태가 잘 되는지에 대한 테스트코드 작성이 잘 안되네요.
