### ISSUE TITLE
테스트 코드 작성을 위한 JUnit 라이브러리 적용

### ISSUE THREAD

**Issue by redjen8** [2022-cau-design-pattern-09/life-game#4]
AS-IS : 테스트 코드를 별도의 main 클래스에 작성하여 테스트를 수헹
TO-BE : JUnit5 라이브러리를 사용하여 자동화된 테스트 수행을 목적으로 합니다.
기존 별도의 main 클래스로 작성되었던 테스트들 또한 JUnit 라이브러리를 사용하여 테스트를 수행해야 한다고 생각합니다.

**Comment by tjwjdgus12** [comment]
JUnit 테스트 환경을 구축했습니다.
